meta:
  aws:
    az: (( param "specify availability zone" ))

compilation:
  cloud_properties:
    availability_zone: (( grab meta.aws.az ))
    instance_type: m3.large

resource_pools:
- name: default
  network: default
  stemcell:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
    version: latest
  cloud_properties:
    instance_type: m3.large
    availability_zone: (( grab meta.aws.az ))

- name: master
  network: default
  stemcell:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
    version: latest
  cloud_properties:
    instance_type: m3.large
    availability_zone: (( grab meta.aws.az ))
    iam_instance_profile: (( param "specify master instance profile" ))

- name: minion
  network: default
  stemcell:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
    version: latest
  cloud_properties:
    instance_type: c3.2xlarge
    availability_zone: (( grab meta.aws.az ))
    iam_instance_profile: (( param "specify minion instance profile" ))

jobs:
- name: consul
  instances: 3
  networks:
  - name: default
    static_ips: (( static_ips(0, 1, 2) ))

- name: etcd
  instances: 3
  networks:
  - name: default
    static_ips: (( static_ips(3, 4, 5) ))

- name: master
  instances: 3
  networks:
  - name: default
    static_ips: (( static_ips(6, 7, 8) ))

- name: minion
  instances: 2
  networks:
  - name: default
    static_ips: (( static_ips(9, 10) ))

- name: guestbook-example
  lifecycle: errand
  instances: 1
  networks:
  - name: default

properties:
  nodes: (( grab jobs.master.networks.default.static_ips jobs.minion.networks.default.static_ips ))
  apiserver:
    ip: (( grab jobs.etcd.networks.default.static_ips.[0] ))
    host: (( grab jobs.master.networks.default.static_ips.[0] ))
    hosts: (( grab jobs.master.networks.default.static_ips ))
  consul:
    join_host: (( grab jobs.consul.networks.default.static_ips.[0] ))
    join_hosts: (( grab jobs.consul.networks.default.static_ips ))
  etcd:
    machines: (( grab jobs.etcd.networks.default.static_ips ))
